"""Error codes catalog (Phase 4).

Single source of truth for all AniVault error codes.
"""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    """Error codes for AniVault application."""

    # File System Errors
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    DIRECTORY_NOT_FOUND = "DIRECTORY_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    FILE_PERMISSION_DENIED = "FILE_PERMISSION_DENIED"
    INVALID_PATH = "INVALID_PATH"
    DIRECTORY_CREATION_FAILED = "DIRECTORY_CREATION_FAILED"
    FILE_ACCESS_DENIED = "FILE_ACCESS_DENIED"
    FILE_ACCESS_ERROR = "FILE_ACCESS_ERROR"
    FILE_DELETE_ERROR = "FILE_DELETE_ERROR"
    FILE_CREATE_ERROR = "FILE_CREATE_ERROR"
    FILE_READ_ERROR = "FILE_READ_ERROR"
    FILE_WRITE_ERROR = "FILE_WRITE_ERROR"

    # Network and API Errors
    NETWORK_ERROR = "NETWORK_ERROR"
    API_RATE_LIMIT = "API_RATE_LIMIT"
    API_AUTHENTICATION_FAILED = "API_AUTHENTICATION_FAILED"
    API_REQUEST_FAILED = "API_REQUEST_FAILED"
    API_TIMEOUT = "API_TIMEOUT"
    API_SERVER_ERROR = "API_SERVER_ERROR"

    # TMDB API Specific
    TMDB_API_CONNECTION_ERROR = "TMDB_API_CONNECTION_ERROR"
    TMDB_API_AUTHENTICATION_ERROR = "TMDB_API_AUTHENTICATION_ERROR"
    TMDB_API_RATE_LIMIT_EXCEEDED = "TMDB_API_RATE_LIMIT_EXCEEDED"
    TMDB_API_REQUEST_FAILED = "TMDB_API_REQUEST_FAILED"
    TMDB_API_TIMEOUT = "TMDB_API_TIMEOUT"
    TMDB_API_SERVER_ERROR = "TMDB_API_SERVER_ERROR"
    TMDB_API_INVALID_RESPONSE = "TMDB_API_INVALID_RESPONSE"
    TMDB_API_MEDIA_NOT_FOUND = "TMDB_API_MEDIA_NOT_FOUND"
    TMDB_API_INVALID_MEDIA_TYPE = "TMDB_API_INVALID_MEDIA_TYPE"

    # File Grouping and Organization
    FILE_GROUPING_FAILED = "FILE_GROUPING_FAILED"
    ORGANIZATION_PLAN_FAILED = "ORGANIZATION_PLAN_FAILED"
    RESOLUTION_DETECTION_FAILED = "RESOLUTION_DETECTION_FAILED"
    RESOLUTION_GROUPING_FAILED = "RESOLUTION_GROUPING_FAILED"
    RESOLUTION_COMPARISON_FAILED = "RESOLUTION_COMPARISON_FAILED"
    SUBTITLE_MATCHING_FAILED = "SUBTITLE_MATCHING_FAILED"
    SUBTITLE_GROUPING_FAILED = "SUBTITLE_GROUPING_FAILED"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    INVALID_METADATA = "INVALID_METADATA"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    TYPE_COERCION_ERROR = "TYPE_COERCION_ERROR"

    # Parsing
    PARSING_ERROR = "PARSING_ERROR"
    FILENAME_PARSE_FAILED = "FILENAME_PARSE_FAILED"
    METADATA_PARSE_FAILED = "METADATA_PARSE_FAILED"

    # Cache
    CACHE_ERROR = "CACHE_ERROR"
    CACHE_READ_FAILED = "CACHE_READ_FAILED"
    CACHE_WRITE_FAILED = "CACHE_WRITE_FAILED"
    CACHE_CORRUPTION = "CACHE_CORRUPTION"
    CACHE_CORRUPTED = "CACHE_CORRUPTED"
    CACHE_SERIALIZATION_ERROR = "CACHE_SERIALIZATION_ERROR"

    # Configuration
    CONFIG_ERROR = "CONFIG_ERROR"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    MISSING_CONFIG = "MISSING_CONFIG"
    CONFIG_MISSING = "CONFIG_MISSING"
    INVALID_CONFIG = "INVALID_CONFIG"
    CONFIG_INVALID = "CONFIG_INVALID"

    # Security
    INVALID_TOKEN = "INVALID_TOKEN"  # noqa: S105
    TOKEN_EXPIRED = "TOKEN_EXPIRED"  # noqa: S105
    TOKEN_MALFORMED = "TOKEN_MALFORMED"  # noqa: S105
    ENCRYPTION_FAILED = "ENCRYPTION_FAILED"
    DECRYPTION_FAILED = "DECRYPTION_FAILED"

    # Dependency
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
    DEPENDENCY_VERSION_MISMATCH = "DEPENDENCY_VERSION_MISMATCH"

    # Application
    APPLICATION_ERROR = "APPLICATION_ERROR"
    UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
    OPERATION_CANCELLED = "OPERATION_CANCELLED"
    OPERATION_TIMEOUT = "OPERATION_TIMEOUT"

    # CLI
    INVALID_COMMAND = "INVALID_COMMAND"
    COMMAND_EXECUTION_FAILED = "COMMAND_EXECUTION_FAILED"
    CLI_COMMAND_FAILED = "CLI_COMMAND_FAILED"
    CLI_INVALID_ARGUMENTS = "CLI_INVALID_ARGUMENTS"
    CLI_CONFIGURATION_ERROR = "CLI_CONFIGURATION_ERROR"
    CLI_DIRECTORY_VALIDATION_FAILED = "CLI_DIRECTORY_VALIDATION_FAILED"
    CLI_SCAN_COMMAND_FAILED = "CLI_SCAN_COMMAND_FAILED"
    CLI_ORGANIZE_COMMAND_FAILED = "CLI_ORGANIZE_COMMAND_FAILED"
    CLI_MATCH_COMMAND_FAILED = "CLI_MATCH_COMMAND_FAILED"
    CLI_VERIFY_COMMAND_FAILED = "CLI_VERIFY_COMMAND_FAILED"
    CLI_PIPELINE_EXECUTION_FAILED = "CLI_PIPELINE_EXECUTION_FAILED"
    CLI_METADATA_ENRICHMENT_FAILED = "CLI_METADATA_ENRICHMENT_FAILED"
    CLI_FILE_ORGANIZATION_FAILED = "CLI_FILE_ORGANIZATION_FAILED"
    CLI_UNEXPECTED_ERROR = "CLI_UNEXPECTED_ERROR"
    CLI_COMMAND_INTERRUPTED = "CLI_COMMAND_INTERRUPTED"
    CLI_OUTPUT_ERROR = "CLI_OUTPUT_ERROR"

    # Business Logic
    BUSINESS_LOGIC_ERROR = "BUSINESS_LOGIC_ERROR"
    DATA_PROCESSING_ERROR = "DATA_PROCESSING_ERROR"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"

    # Rate Limiting and Concurrency
    RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR"
    CONCURRENCY_ERROR = "CONCURRENCY_ERROR"
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE"
    RESOURCE_CLEANUP_ERROR = "RESOURCE_CLEANUP_ERROR"

    # Infrastructure
    INFRASTRUCTURE_ERROR = "INFRASTRUCTURE_ERROR"

    # Pipeline
    PIPELINE_INITIALIZATION_ERROR = "PIPELINE_INITIALIZATION_ERROR"
    PIPELINE_EXECUTION_ERROR = "PIPELINE_EXECUTION_ERROR"
    PIPELINE_SHUTDOWN_ERROR = "PIPELINE_SHUTDOWN_ERROR"
    PIPELINE_COMPONENT_ERROR = "PIPELINE_COMPONENT_ERROR"
    QUEUE_OPERATION_ERROR = "QUEUE_OPERATION_ERROR"
    WORKER_POOL_ERROR = "WORKER_POOL_ERROR"
    SCANNER_ERROR = "SCANNER_ERROR"
    PARSER_ERROR = "PARSER_ERROR"
    COLLECTOR_ERROR = "COLLECTOR_ERROR"
