# Prometheus configuration for AniVault monitoring
# Place this file in your Prometheus configuration directory

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "anivault_rules.yml"  # Uncomment if you have custom alerting rules

scrape_configs:
  # AniVault application metrics
  - job_name: 'anivault'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Optional: Add labels to identify the instance
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):(\d+)'
        replacement: '${1}:${2}'
      - target_label: application
        replacement: 'anivault'
      - target_label: environment
        replacement: 'development'  # Change to 'production' for production deployments

  # Optional: Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Optional: Remote write configuration for external storage
# remote_write:
#   - url: 'http://remote-storage-adapter/api/v1/write'
#     queue_config:
#       max_samples_per_send: 1000
#       batch_send_deadline: 5s

# Optional: Remote read configuration
# remote_read:
#   - url: 'http://remote-storage-adapter/api/v1/read'
