"""Initial migration with existing tables

Revision ID: 3ff80129897d
Revises:
Create Date: 2025-09-19 07:51:13.918919

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3ff80129897d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
