"""Add version column to parsed files.

Revision ID: 595e783b8c37
Revises: 63b04737b492
Create Date: 2025-09-20 21:18:53.547893

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "595e783b8c37"
down_revision: str | Sequence[str] | None = "63b04737b492"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anime_metadata", sa.Column("version", sa.Integer(), nullable=False))
    op.create_index("idx_anime_metadata_version", "anime_metadata", ["version"], unique=False)
    op.create_index(
        op.f("ix_anime_metadata_first_air_date"), "anime_metadata", ["first_air_date"], unique=False
    )
    op.create_index(
        op.f("ix_anime_metadata_korean_title"), "anime_metadata", ["korean_title"], unique=False
    )
    op.create_index(
        op.f("ix_anime_metadata_original_title"), "anime_metadata", ["original_title"], unique=False
    )
    op.create_index(
        op.f("ix_anime_metadata_popularity"), "anime_metadata", ["popularity"], unique=False
    )
    op.create_index(op.f("ix_anime_metadata_status"), "anime_metadata", ["status"], unique=False)
    op.create_index(op.f("ix_anime_metadata_title"), "anime_metadata", ["title"], unique=False)
    op.create_index(op.f("ix_anime_metadata_version"), "anime_metadata", ["version"], unique=False)
    op.create_index(
        op.f("ix_anime_metadata_vote_average"), "anime_metadata", ["vote_average"], unique=False
    )
    op.add_column("parsed_files", sa.Column("version", sa.Integer(), nullable=False))
    op.drop_index(op.f("idx_parsed_files_file_path"), table_name="parsed_files")
    op.create_index("idx_parsed_files_file_path", "parsed_files", ["file_path"], unique=False)
    op.create_index("idx_parsed_files_version", "parsed_files", ["version"], unique=False)
    op.create_index(op.f("ix_parsed_files_episode"), "parsed_files", ["episode"], unique=False)
    op.create_index(
        op.f("ix_parsed_files_file_extension"), "parsed_files", ["file_extension"], unique=False
    )
    op.create_index(op.f("ix_parsed_files_file_hash"), "parsed_files", ["file_hash"], unique=False)
    op.create_index(op.f("ix_parsed_files_file_path"), "parsed_files", ["file_path"], unique=True)
    op.create_index(op.f("ix_parsed_files_filename"), "parsed_files", ["filename"], unique=False)
    op.create_index(
        op.f("ix_parsed_files_is_processed"), "parsed_files", ["is_processed"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_files_metadata_id"), "parsed_files", ["metadata_id"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_files_parsed_title"), "parsed_files", ["parsed_title"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_files_release_group"), "parsed_files", ["release_group"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_files_resolution"), "parsed_files", ["resolution"], unique=False
    )
    op.create_index(op.f("ix_parsed_files_season"), "parsed_files", ["season"], unique=False)
    op.create_index(op.f("ix_parsed_files_version"), "parsed_files", ["version"], unique=False)
    op.create_index(op.f("ix_parsed_files_year"), "parsed_files", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parsed_files_year"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_version"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_season"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_resolution"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_release_group"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_parsed_title"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_metadata_id"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_is_processed"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_filename"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_file_path"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_file_hash"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_file_extension"), table_name="parsed_files")
    op.drop_index(op.f("ix_parsed_files_episode"), table_name="parsed_files")
    op.drop_index("idx_parsed_files_version", table_name="parsed_files")
    op.drop_index("idx_parsed_files_file_path", table_name="parsed_files")
    op.create_index(op.f("idx_parsed_files_file_path"), "parsed_files", ["file_path"], unique=1)
    op.drop_column("parsed_files", "version")
    op.drop_index(op.f("ix_anime_metadata_vote_average"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_version"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_title"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_status"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_popularity"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_original_title"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_korean_title"), table_name="anime_metadata")
    op.drop_index(op.f("ix_anime_metadata_first_air_date"), table_name="anime_metadata")
    op.drop_index("idx_anime_metadata_version", table_name="anime_metadata")
    op.drop_column("anime_metadata", "version")
    # ### end Alembic commands ###
