[app]
name = "AniVault"
version = "0.1.0"
description = "Anime Collection Management System"
debug = false

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "logs/anivault.log"
max_bytes = 10485760
backup_count = 5
console_output = true

[tmdb]
base_url = "https://api.themoviedb.org/3"
api_key = "c479f9ce20ccbcc06dbcce991a238120"
timeout = 30
retry_attempts = 3
retry_delay = 1.0
rate_limit_delay = 0.25

[file_processing]
supported_extensions = [ ".mkv", ".mp4", ".avi", ".mov", ".wmv", ".flv", ".m4v", ".webm",]
batch_size = 100
max_workers = 4
timeout = 300

[cache]
enabled = true
ttl = 3600
max_size = 1000
backend = "memory"

[performance]
memory_limit = "2GB"
cpu_limit = 4
enable_profiling = false
profile_output = "logs/profiling.json"
