# AniVault Configuration Settings

# Application Settings
app:
  name: "AniVault"
  version: "3.0.0"
  description: "Anime Collection Management System"
  debug: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/anivault.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  console_output: true

# TMDB API Configuration
tmdb:
  base_url: "https://api.themoviedb.org/3"
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0
  rate_limit_delay: 0.25  # 250ms between requests

# File Processing Settings
file_processing:
  supported_extensions:
    - ".mkv"
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".wmv"
    - ".flv"
    - ".m4v"
    - ".webm"
  batch_size: 100
  max_workers: 4
  timeout: 300  # 5 minutes

# Cache Settings
cache:
  enabled: true
  ttl: 3600  # 1 hour
  max_size: 1000
  backend: "memory"  # memory, redis, sqlite

# Performance Settings
performance:
  memory_limit: "2GB"
  cpu_limit: 4
  enable_profiling: false
  profile_output: "logs/profiling.json"
