"""Domain constants for entity validation (Phase 5)."""

from anivault.domain.constants.entity_validation import (
    EMPTY_FILE_TYPE_ERROR,
    EMPTY_TITLE_ERROR,
    EPISODE_NEGATIVE_ERROR_TEMPLATE,
    MAX_VOTE_AVERAGE,
    MAX_YEAR,
    MIN_VOTE_AVERAGE,
    MIN_YEAR,
    SEASON_NEGATIVE_ERROR_TEMPLATE,
    VOTE_AVERAGE_RANGE_ERROR_TEMPLATE,
    YEAR_RANGE_ERROR_TEMPLATE,
)

__all__ = [
    "EMPTY_FILE_TYPE_ERROR",
    "EMPTY_TITLE_ERROR",
    "EPISODE_NEGATIVE_ERROR_TEMPLATE",
    "MAX_VOTE_AVERAGE",
    "MAX_YEAR",
    "MIN_VOTE_AVERAGE",
    "MIN_YEAR",
    "SEASON_NEGATIVE_ERROR_TEMPLATE",
    "VOTE_AVERAGE_RANGE_ERROR_TEMPLATE",
    "YEAR_RANGE_ERROR_TEMPLATE",
]
